apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Values.metadata.labels.app }}
