apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: {{ .Values.persistent.pvc.name }}
            mountPath: {{ .Values.persistent.pvc.dirpath }}
      volumes:
      - name: {{ .Values.persistent.pvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistent.pvc.name }}
