apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistent.pvc.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistent.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistent.capacity }}
